server:
 port: 8090
spring:
  application:
   name: icycraft-comment
  datasource:
    password: 1234
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/blog
    username: root
  jpa:
    show-sql: true
eureka:
 client:
  serviceUrl:
   defaultZone: http://127.0.0.1:8761/eureka/