server:
 port: 8089
spring:
  application:
   name: icycraft-blogDetail
  redis:
   database: 0
   password: wsky357951
   port: 6379
   host: 111.230.17.188
   timeout: 100000
eureka:
 client:
  serviceUrl:
   defaultZone: http://127.0.0.1:8761/eureka/
feign:
  client:
    config:
      default:           #服务名，填写default为所有服务
        connectTimeout: 100000
        readTimeout: 1200000